### ISSUE TITLE
请教login script能否打开一个system权限的cmd?

### ISSUE THREAD

**Issue by xssssrf** [3gstudent/feedback#11]
看了您"Logon Scripts的后门实现思路"这篇文章,我在想能否用login script去写入一个无文件的wmi后门,但是这需要system权限,而login script是登陆的普通用户的权限.
请问有没有什么办法切换到system呢?

**Comment by 3gstudent** [comment]
@sn00pyd0g3 
需要的是管理员权限，不需要system权限

使用login script无法切换到管理员权限，得需要配合其他的提权技巧
