### ISSUE TITLE
在高版本系统上还需要考虑lsa RunAsPPL的设置

### ISSUE THREAD

**Issue by wyzzoo** [3gstudent/feedback#13]
https://3gstudent.github.io/3gstudent.github.io/Password-Filter-DLL%E5%9C%A8%E6%B8%97%E9%80%8F%E6%B5%8B%E8%AF%95%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8/ 针对这篇的评论。
https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection

**Comment by 3gstudent** [comment]
感谢，等我研究一下 @wyzzoo

**Comment by 3gstudent** [comment]
@wyzzoo 
https://3gstudent.github.io/3gstudent.github.io/%E9%85%8D%E7%BD%AEAdditional-LSA-Protection%E7%9B%91%E6%8E%A7Password-Filter-DLL/
