### ISSUE TITLE
请问师傅编译64位的dll您也是使用的vc6.0吗？

### ISSUE THREAD

**Issue by xnianq** [3gstudent/feedback#21]
请问师傅编译64位的dll您也是使用的vc6.0吗？

**Comment by 3gstudent** [comment]
vs2012

**Comment by xnianq** [comment]
在编译的时候有什么特殊的配置吗？我使用vs系列编译出来的dll，无法在没有安装vs的机器上执行，网上找了半天也没找到原因，才使用的vc...但是x64的vc真的无能为力呀，所以想请教一下师傅

**Comment by 3gstudent** [comment]
https://blog.csdn.net/albertsh/article/details/52838419

**Comment by xnianq** [comment]
师傅 这篇文章我之前也看过了，这三种方法编译的我都试了一遍，生成过程为：win32控制台应用程序->dll->空白项目->testdll.cpp,testdll.h,编译成功之后在本地可以执行，但是到了其他机器上就执行不了。
![image](https://user-images.githubusercontent.com/17513849/44511154-31ece680-a6e9-11e8-89c7-f8f2bbe13738.png)

**Comment by xnianq** [comment]
谢谢师傅，搞定了，不用.h，在别的系统上就可以运行了，非常感谢
