### ISSUE TITLE
使用Go语言开发socks代理工具 session存在会覆盖问题

### ISSUE THREAD

**Issue by shownb** [3gstudent/feedback#24]
参考的那个github也会。如果作为demo，可以忽略。
还有在android环境下会存在dns解析问题。

**Comment by 3gstudent** [comment]
具体描述一下？

**Comment by shownb** [comment]
listenforsocks函数的
	for {
		conn, err := ln.Accept()
		log.Println("Got a client")
		if err != nil {
			fmt.Fprintf(os.Stderr, "Errors accepting!")
		}
		// Add connection to yamux
		session, err = yamux.Client(conn, nil)
	}
如果有人连过来就覆盖session

**Comment by 3gstudent** [comment]
如果只有一个用户就不会有这个问题吧

**Comment by shownb** [comment]
不会。

**Comment by 3gstudent** [comment]
那先没必要改，等有空的时候再完善一下代码
