### ISSUE TITLE
dll文件不存在，如何去导出函数表呢？

### ISSUE THREAD

**Issue by xxxxxyyyy** [3gstudent/feedback#25]
师傅你好，我在看你的 “利用可信目录进行bypas UAC“ 的文章，觉得挺有意思，自己尝试去复现了下，有2个问题想请教一下：

1.请问你测试的具体操作系统版本是？我用win7 x64 sp1 中文版，没有发现winsat.exe 存在autoElevate为true。

2.我寻找到了其它存在可以自动提升权限的exe,通过Process Monitor去查看它的启动过程，查看您文章里是说关注 NOT FOUND 的dll，但是既然这个dll无法找到，那我怎么去导出它的函数表呢？

谢谢！

**Comment by 3gstudent** [comment]
1. 没有winsat.exe就换一个，方法文中也有介绍
2. dll在c:\windows\system32下应该可以找到

**Comment by xxxxxyyyy** [comment]
感谢回答！

之前是我没有看懂文章意思，我是在真实路径去执行的(c:\windows\system32\*.exe),然后开启 process monitor，去监控进程，操作方法不对。

不过我现在知道了正确的操作方式，我将所有含有autoElevate 属性为true的exe，全部拷贝到了(c:\windows  \system32\)里面，运行其中一个exe后，然后找NOT FOUND的dll，通过exportstoc导出函数表来生成自己的dll,再将该dll改名放置到(c:\windows \system32\)目录，但是奇怪的是我dll里面的payload ("start calc")并不执行. 在process monitor 里面看到有加载了我这个dll，我接连试了多个其它的exe，但是依然不会执行我的payload。很不解。

我用同样的方法去劫持某些存在dll劫持漏洞的程序(比如早期的putty、tftp)，都可以执行我的payload.

**Comment by 3gstudent** [comment]
按你的描述来看是dll的问题，尝试以下方法：
- 换其他payload试试看
- 如果是64位系统，dll是不是也是64位
- 命令行下启动exe需要绝对路径

**Comment by xxxxxyyyy** [comment]
可以了，就是你说的 64位系统，用的32位 dll 。
自己瞎折腾了几天。
感谢耐心解答！ ！
