### ISSUE TITLE
模拟IE下载的应用场景是什么

### ISSUE THREAD

**Issue by st0rmspirit** [3gstudent/feedback#26]
文中讲到绕过白名单的防护，没明白是什么样的场景。环境中不允许IE下载，但是可以通过模拟IE去下载？  如果IE可以下载，直接去下载就行啊。辛苦楼主

https://3gstudent.github.io/3gstudent.github.io/%E6%B8%97%E9%80%8F%E6%8A%80%E5%B7%A7-%E6%A8%A1%E6%8B%9FIE%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6/

**Comment by 3gstudent** [comment]
防火墙记录有下载行为的进程
