### ISSUE TITLE
Win7 x64 下HideAdmin工作不正常

### ISSUE THREAD

**Issue by sunlewuyou** [3gstudent/feedback#31]
https://github.com/binlmmhc/HideAdmin
从这个地方下载的源码编译HideAdmin.exe，使用起来很不稳定，偶尔能成功创建出来隐藏用户，而且还是users用户组的，感觉很不稳定，老师能提供一个您有的稳定版本吗？

**Comment by 3gstudent** [comment]
不能，原理不复杂，你自己研究再调试一下你的收获会更大。

**Comment by sunlewuyou** [comment]
好的，这几天快学习得没有白天黑夜了。看来要好好学学一下C了。
