### ISSUE TITLE
https://3gstudent.github.io/%E6%B8%97%E9%80%8F%E5%9F%BA%E7%A1%80-%E6%B4%BB%E5%8A%A8%E7%9B%AE%E5%BD%95%E4%BF%A1%E6%81%AF%E7%9A%84%E8%8E%B7%E5%8F%96/

### ISSUE THREAD

**Issue by qiaomu2333** [3gstudent/feedback#34]
你这篇文章里绑定adsi的方式，为什么我用我的程序就不可以，反而必须要指定域用户的用户名和密码，这里有什么需要注意的嘛；
![image](https://user-images.githubusercontent.com/48524416/72242287-ffb48f80-3623-11ea-9869-8fa3b42c90da.png)
谢谢

**Comment by 3gstudent** [comment]
你是在域内吗
