### ISSUE TITLE
关于processhider

### ISSUE THREAD

**Issue by go-spider** [3gstudent/feedback#35]
怎么在win10全局hook？

**Comment by 3gstudent** [comment]
百度有很多资料，你可以具体描述一下你的问题

**Comment by go-spider** [comment]
@3gstudent 新开一个查看进程的程序，你没注入dll是无法隐藏进程的。

**Comment by 3gstudent** [comment]
win10.1803测试没有问题
![111](https://user-images.githubusercontent.com/15814408/75201464-77d5af80-57a3-11ea-8a1a-c539de4136f2.png)

**Comment by go-spider** [comment]
@3gstudent 
https://3gstudent.github.io/%E5%88%A9%E7%94%A8globalAPIhooks%E5%9C%A8Win7%E7%B3%BB%E7%BB%9F%E4%B8%8B%E9%9A%90%E8%97%8F%E8%BF%9B%E7%A8%8B/
1、用这篇文章里面的设置注册表键值HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\Windows任何使用到User32.DLL的进程都会被AppInit_DLLs指向的DLL所注入，如你所说该方法只支持Win7 和 Windows Server 2008 R2，不支持更高版本如Win8、Server2012。
2、使用SetWindowsHookEx函数可以全局注入dll到有窗口的进程中去，命令行程序就不行了。
我是想知道win10上有什么比较好的方法自动注入dll到新建的进程里面。

**Comment by 3gstudent** [comment]
https://github.com/fdiskyou/injectAllTheThings

https://github.com/3gstudent/Inject-dll-by-APC

都可以试试

**Comment by go-spider** [comment]
@3gstudent 
我想表达的意思是监控新产生的进程并注入dll，这就可以做到全局hook了，不是注入方法。

**Comment by 3gstudent** [comment]
获得进程列表，指定进程进行hook：

https://github.com/M00nRise/ProcessHider/blob/3f8dc3e2a1505df321f4e74427b230555123556e/ProcessHider/Daemon.cpp#L70
