### ISSUE TITLE
Powershell tricks::Hide Process by kd.exe 文章内容重复出现

### ISSUE THREAD

**Issue by Malayke** [3gstudent/feedback#4]
[《Powershell tricks::Hide Process by kd.exe 》](https://3gstudent.github.io/3gstudent.github.io/Powershell-tricks-Hide-Process-by-kd.exe/)文章内容重复出现了两次

**Comment by 3gstudent** [comment]
3q，已更改

**Comment by Malayke** [comment]
三好学生的博客一定不要停止更新了，我等学渣是博客的忠实膜拜者～

**Comment by 3gstudent** [comment]
@Malayke 放心吧，尽量每周一篇
