### ISSUE TITLE
大佬，xpn的addsecuritypackage_rawrpc那一个头文件，两个c文件是怎么编译的

### ISSUE THREAD

**Issue by um3ha4a** [3gstudent/feedback#42]
https://gist.github.com/xpn/c7f6d15bf15750eae3ec349e7ec2380e
这个，我编译报大量的错，是sdk的版本问题吗

**Comment by 3gstudent** [comment]
要看你具体的错误

VS2015下可正常编译，如果编译成在静态库中使用MFC，需要添加如下代码：#pragma comment(lib, "Rpcrt4.lib")

其他代码不用改动

**Comment by uemahra** [comment]
我发现是把c改成cpp就可以了，但是，他源码里好像没有往system32里写xpn.log这个文件吧，大佬是自己加的吗

**Comment by nbsp-null** [comment]
工程属性从UNICODE改成多字节符就可以了
#pragma comment(lib, "Rpcrt4.lib") vs2019好像不行

**Comment by 3gstudent** [comment]
我用的vs2015
