### ISSUE TITLE
3gstudent yyds

### ISSUE THREAD

**Issue by ltdragonfly** [3gstudent/feedback#48]
hello!

recently, i tested your awsome python script: ewsManage_Downloader.py with a user's NTLM hash on office365:

ewsManage_Downloader.py outlook.office.com 443 ntlmhash <domain> <user> <password> download

but i get a reply:

NTLM Auth not offered by URL, offered protocols: Basic Realm=""

how can i resolve this?

**Comment by 3gstudent** [comment]
Office 365 does not support NTLM authentication.
:(

**Comment by ltdragonfly** [comment]
i am sorry to hear that...
thank you very much
