### ISSUE TITLE
请教一下师傅关于vSphere开发指南5——LDAP的问题

### ISSUE THREAD

**Issue by helloyw** [3gstudent/feedback#49]
请教一下关于《vSphere开发指南5——LDAP》这篇文章vCenter上通过LDAP数据库添加管理员用户的方法，/opt/likewise/bin/lwregshell list_values '[HKEY_THIS_MACHINE\services\vmdir]'通过该命令读取出来的password，我尝试文中提供脚本还是我自己去连ldap都会提示我凭证有问题这是什么问题呢
![IMG_9156](https://user-images.githubusercontent.com/32027872/144781482-f64586ac-e36e-4931-b1f8-d020599d61a6.PNG)
？

**Comment by 3gstudent** [comment]
大概率是连接参数问题

**Comment by helloyw** [comment]
好谢谢师傅解答
