### ISSUE TITLE
关于《渗透技巧——利用netsh抓取连接文件服务器的NTLMv2 Hash》的一个小问题

### ISSUE THREAD

**Issue by m0rning0o0** [3gstudent/feedback#51]
最近拜读了师傅的《渗透技巧——利用netsh抓取连接文件服务器的NTLMv2 Hash》这篇文章，在调试代码的时候发现了一个问题，在我的测试环境中（win7+server08），smbv2流量中用户名和域名的偏移并不是固定的 88，NTLMResPonse 的偏移也不是固定的 174，感觉可能还是处理时识别偏移位置比较好。另外师傅的代码是python2下的，我创建了一个[python3的副本](https://github.com/m0rning0o0/Notes/blob/main/Get_NTLMv2-Hash/GetNTLMv2.py)。

**Comment by 3gstudent** [comment]
嗯嗯，数据包保存到本地后，改一下偏移自动提取就好。
