### ISSUE TITLE
question

### ISSUE THREAD

**Issue by VVeakee** [3gstudent/feedback#53]
请问生成msi后如何以命令行无ui页面运行啊?
已试过msiexec /i /qn UserAdd.msi和msiexec /i /q UserAdd.msi
第一种没有页面添加不了用户
第二种会弹出ui页面

**Comment by 3gstudent** [comment]
你在什么版本的系统下测试的

**Comment by VVeakee** [comment]
win10专业版

**Comment by 3gstudent** [comment]
Win10应该是改了，我当时测试的时候都在win7做的

**Comment by VVeakee** [comment]
好的，感谢，我去win7试试
