### ISSUE TITLE
LaZagne工具利用源码编译exe时的一个问题

### ISSUE THREAD

**Issue by burnegg** [3gstudent/feedback#9]
<本地密码查看工具LaZagne中的自定义脚本开发>文章中提到
https://github.com/AlessandroZ/LaZagne 中
Windows\lazagne\softwares\memory\memorydump.py: import memory 语句无法正确编译，改成memory_profiler后虽然成功编译，但是运行memory模块时会报错 Process没有list方法。
我反编译了原repo的exe，发现原作者用的是memorpy模块，并且该源代码处有提示
```
# create a symbolic link on Windows
# mklink /J memorpy ..\..\..\..\external\memorpy\memorpy
```
我自己测试先执行
```
pip install https://github.com/n1nj4sec/memorpy/archive/master.zip
```
然后把import memory换成import memorpy 就能正确执行了。

**Comment by 3gstudent** [comment]
@burnegg 
原来使用memory_profiler确实有这个问题，感谢提醒

但是使用import memorpy，你有没有遇到无法正常执行的问题，卡在输出页面

**Comment by burnegg** [comment]
@3gstudent 我测试了win7-win10，没遇到这种情况。。

**Comment by 3gstudent** [comment]
@burnegg 再次测试完成，原文已修正，十分感谢
